promise
===================
Promise对象，可以将异步操作以同步操作的流程表达出来，避免了层层嵌套的回调函数。
###  用法
```
const promise = new Promise(function(resolve, reject) {
  // code
});
```
Promise构造函数接受一个函数作为参数，这个参函数也有两个参数resolve和reject，它们也是函数。resolve函数将Promise对象的状态从“未完成pending”变为“成功fulfilled”，所以在异步操作成功时调用；reject函数将Promise对象的状态从“未完成pending”变为“失败rejected”，所以在异步操作失败时调用，这两个函数都可以传递参数。

then方法是Promise对象“成功”和“失败”的回调函数。有两个函数作为参数，这两个参函数分别接受resolved（成功）状态和rejected（失败）状态传递的值为参数：
```
promise.then(function(value) {
  // 异步成功后需要执行的代码
}, function(error) {
  // 异步失败后需要执行的代码
});
```
第二个函数是可选的，不一定要提供。

注意：**Promise 创建后就会立即执行，自身是同步的，then是异步的**。所以，用Promise的时候一般是包在一个函数中，在需要的时候去运行这个函数，如：
```
function runPromise(){
    const promise = new Promise(function(resolve, reject) {
      // code
    });
    return promise;
}
```

下面是异步加载图片的例子。
```
function loadImageAsync(url) {
  return new Promise(function(resolve, reject) {
    const image = new Image();

    image.onload = function() {
      resolve(image);
    };

    image.onerror = function() {
      reject(new Error('Could not load image at ' + url));
    };

    image.src = url;
  });
}

loadImageAsync("imgSrc").then(function(value){
  //异步成功的回调
  document.body.appendChild(value)
},function(error){
  //异步失败的回调
  console.error(error)
})
```
###  链式调用
then支持执行链式调用：
```
doSomething().then(function(result) {
  return doSomethingElse(result);
})
.then(function(newResult) {
  return doThirdThing(newResult);
})
.catch(failureCallback);
```
如果前一个then，返回值还是一个Promise对象，那么后一个then，就会等待该Promise对象的状态发生变化，才会被调用。

如果要跳出链式调用，需要返回pedding状态的promise。
```
promise.then(()=>{
  return new Promise(()=>{})
}).then(()=>{
  //不会执行
})
```
###  catch方法
Promise对象还有一个catch方法来收集错误：

	promise.then(function(data){
		console.log(data);
	}).catch(function(error){
		console.log(error)
	})

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止，catch方法则优先捕获最顶层（promise）的错误。所以，可以在最后添加catch方法。

	loadImageAsync("imgSrc1").then((image)=>{
		document.body.appendChild(image);
		// 注意，then()执行后需要返回新的promise用于链式调用
		return loadImageAsync("imgSrc2")
	}).then((image)=>{
		document.body.appendChild(image);
	}).catch((error)={
		console.log(error)
	})
Promise 内部的错误会终止后续所有then的运行，并传递到catch内，但是不会影响到 Promise 外部的代码。

###  finally方法
一般放在实例链的最后，不管 Promise 对象最后状态如何，都会执行的操作，finally方法没有参数。

###  静态all方法
all()方法将多个 Promise 实例的数组合成一个新的 Promise 实例。
```
let p = Promise.all([p1, p2, p3]);
```
上例p的状态由p1、p2、p3决定，p1、p2、p3都成功，则p变为成功，then传递所有成功的传递值组成的数组，p1、p2、p3有一个失败，则p失败，catch捕获第一个失败的传递值。

###  静态race方法
race()方法也是将多个 Promise 实例合成一个新的 Promise 实例。
```
let p = Promise.race([p1, p2, p3]);
```
上例p的状态由p1、p2、p3决定，但不同于all方法，p1、p2、p3谁先改变状态，p就相应改变状态，传递先改变的promise。
```
const p = Promise.race([
  fetch('/resource-that-may-take-a-while'),
  new Promise(function (resolve, reject) {
    setTimeout(() => reject(new Error('request timeout')), 5000)
  })
]);

p
.then(console.log)
.catch(console.error);
```
上面代码中，如果 5 秒之内fetch方法无法返回结果，就触发rejected。

###  静态any方法
如果所有参数实例都变成rejected状态，包装实例就会变成rejected状态，值保存在err.errors数组，否则状态为resolve，并返回第一个状态resolve的promise。

###  静态resolve()、reject()
Promise.resolve()会返回一个Promise 对象，**状态由根据传入的参数决定**。
如果参数是一个 Promise 实例，那么返回这个实例。或者参数是具有 then 方法的对象，那么返回 Promise 对象，并调用then()。其他就返回一个resolved状态的 Promise 对象。

**then方法和catch方法返回 Promise 对象的状态也是这样**。

Promise.reject()方法返回的 Promise 状态为rejected。
这个状态改变发生在本轮事件循环（event loop）的结尾。
```
setTimeout(function () {
  //下轮事件循环执行
  console.log('third')
}, 0);

Promise.resolve().then(function () {
  //本轮事件循环结尾执行
  console.log('second')
});

console.log('first')
```

###  静态allSettled方法
和实例方法finally类似，allSettled不管每一个promise是成功还是失败，总会在所有的都状态改变后，返回状态为resolve的promise，then的参数是每一个的执行情况组成的数组。